### ISSUE TITLE
Curious about this

### ISSUE THREAD

**Issue by cjcjameson** [rosenhouse/ginkgo-build-flags-issue#1]
@rosenhouse we were fiddling around with build flags in ginkgo and came across this. We don't think we're seeing the issue you've reproduced, but were wondering if you could point to where it got fixed or discussed? Just trying to learn more!

**Comment by rosenhouse** [comment]
@cjcjameson Here you go!  https://github.com/onsi/ginkgo/issues/290

I never really dug into it beyond this.
